pluginManagement {
    plugins {
        id 'net.fabricmc.fabric-loom' version providers.gradleProperty('loom_version').get()
    }
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
    }
}
rootProject.name = 'minecraft-mod-suite'
include 'bedrock-scout'
project(':bedrock-scout').projectDir = file('mods/bedrock-scout')
include 'seed-scout'
project(':seed-scout').projectDir = file('mods/seed-scout')
include 'fry-utilities'
project(':fry-utilities').projectDir = file('mods/fry-utilities')
